# Generated by Django 5.2.7 on 2025-10-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bibit', models.CharField(help_text='Contoh: Bibit Lele Mutiara', max_length=200)),
                ('slug', models.SlugField(help_text='Otomatis terisi, jangan diubah manual', max_length=255, unique=True)),
                ('deskripsi_singkat', models.CharField(help_text='Teks singkat untuk halaman katalog', max_length=255)),
                ('deskripsi_lengkap', models.TextField()),
                ('harga', models.CharField(help_text='Contoh: Mulai dari Rp 500/ekor', max_length=100)),
                ('ukuran', models.CharField(help_text='Contoh: 5-7 cm', max_length=100)),
                ('stok_status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Terbatas', 'Terbatas'), ('Habis', 'Habis')], default='Tersedia', max_length=50)),
                ('gambar_utama', models.ImageField(upload_to='produk_images/')),
                ('is_unggulan', models.BooleanField(default=False, help_text='Centang untuk menampilkan di homepage')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produk Bibit',
                'verbose_name_plural': 'Produk Bibit',
            },
        ),
    ]
